greenplum-db/diskquota

- activetable.c
- enforcement.c
- patch/pg_hooks.patch
- quotamodel.c
1. update hook function points, add smgrdounlinkall hook point
2. refactor code for pg master branch
> Update hook function points in postgres

- concourse/scripts/test_diskquota.sh
- expected/test_primary_failure.out
- sql/test_primary_failure.sql
1. Workaround gprecoverseg issue when the master is done and standby is
activated in the test
> Fix issue during gprecoverseg

- Makefile
- diskquota.c
- diskquota.h
- diskquota_utility.c
- enforcement.c
- expected/test_extension.out
- gp_activetable.c
- init_file
- quotamodel.c
Separate diskquota utility functions into file
diskquota_utility.c
Rename MessageBox to ExtensionDDLMessage.
Cleanup SPI and snapshot when SPI_execute error.
Add more comments for launcher code.
no new feature, so no test needed.
> Refactor diskquota launcher.

- diskquota.h
- diskquota_utility.c
- quotamodel.c
clear the logic in calculate_table_disk_usage
rename lock extension_ddl_lock
add comments for quotamodel
release lock when elog error.
> Refactor quota model.

- concourse/pipeline/pipeline.yml
- concourse/scripts/build_diskquota.sh
- concourse/scripts/test_diskquota.sh
1. Add ubuntu pipeline
2. Add both ubuntu build and test jobs
> Add ubuntu support

- concourse/pipeline/pipeline.yml
- concourse/pipeline/release_pipeline.yml
- concourse/scripts/build_diskquota.sh
- concourse/scripts/test_diskquota.sh
- concourse/tasks/build_diskquota.yml
- concourse/tasks/test_diskquota.yml
* Build pipeline: each platform has one job which contains 2 tasks: build + test
* Release pipeline: contains release + test release for each gpdb binary
release steps:
* build
* test
* push to released bucket
> Update build and release pipelines

- concourse/pipeline/pipeline.yml
- concourse/pipeline/release_pipeline.yml
- concourse/scripts/build_diskquota.sh
1. change filename
2. update script file
> Change release pipeline folder name

- expected/test_table_size.out
- sql/test_table_size.sql
> Fix a typo in #55

- diskquota_schedule
- expected/test_appendonly.out
- sql/test_appendonly.sql
Currently, tests for appendonly relations is missing. This patch adds
one test for that.
Co-Authored-by: Xuebin Su <sxuebin@vmware.com>
Co-Authored-by: Hao Zhang <hzhang2@vmware.com>
> Add test case for appendonly relations.

- tests/regress/expected/test_uncommitted_table_size.out
- tests/regress/sql/test_uncommitted_table_size.sql
This patch fixes flaky test case. No functional change.
> Fix flaky test cases. NFC.

- concourse/pipeline/pipeline.yml
- concourse/pipeline/release_pipeline.yml
- concourse/scripts/build_diskquota.sh
> ci: create rhel8 release build.

- diskquota.c
- tests/regress/diskquota_schedule
- tests/regress/expected/test_recreate.out
- tests/regress/sql/test_recreate.sql
> allow to re-create extension

- tests/regress/diskquota_schedule
- tests/regress/expected/test_ctas_pause.out
- tests/regress/sql/test_ctas_pause.sql
> add test case for pause hardlimit

- diskquota_utility.c
Otherwise compiler reports a warning:
"comparison of constant ‘20’ with boolean expression is always false"
> ereportif uses the 1st param as the condition

- diskquota--1.0--2.0.sql
- diskquota--2.0--1.0.sql
- diskquota--2.0.sql
- diskquota.c
- tests/regress/diskquota_schedule
- tests/regress/expected/test_show_status.out
- tests/regress/sql/test_show_status.sql
```
select * from diskquota.status();
name    | status  
------------+---------
soft limit | enabled
hard limit | enabled
(2 rows)
```
> add diskquota.status() to show if hardlimit or softlimit enabled or not

- tests/regress/expected/test_extension.out
- tests/regress/sql/test_extension.sql
test_extension is a flaky test, it has 30% failure rate.
fix this by adding some waiting time.
> ci: fix flaky test

- concourse/scripts/build_diskquota.sh
No need to have the switch case.
> Simplify the build script

- .clang-format
- .editorconfig
- clang-format is from https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/rHb4DjSd1iI/m/FKPbqwYcBAAJ
- See editorconfig at https://editorconfig.org/
> Add clang-format and editorconfig

- concourse/pipeline/job_def.lib.yml
- concourse/pipeline/pr.yml
- concourse/pipeline/trigger_def.lib.yml
Also fixed a syntax issue in pr.yml
> Set PR pending status when start

- diskquota--1.0.sql
- diskquota.control
The SQL has been formatted by #162.
> Allign SQL with main branch

- CMakeLists.txt
- tests/regress/expected/test_ctas_no_preload_lib.out
- tests/regress/sql/test_ctas_no_preload_lib.sql
「deploy a 'hot fix' to our CI」
> hot fix our CI

- diskquota.c
- tests/regress/expected/test_show_status.out
- tests/regress/sql/test_show_status.sql
> show current binary and schema version

- .editorconfig
- CMakeLists.txt
- cmake/BuildInfo.cmake
- cmake/Git.cmake
- cmake/Gpdb.cmake
- concourse/pipeline/job_def.lib.yml
- concourse/pipeline/res_def.yml
> Upload every build to GCS

- .clang-format
- README.md
- concourse/pipeline/commit.yml
- concourse/pipeline/dev.yml
- concourse/pipeline/job_def.lib.yml
- concourse/pipeline/pr.yml
- concourse/pipeline/res_def.yml
- concourse/scripts/check-clang-format.sh
- diskquota.c
- diskquota.h
- diskquota_utility.c
- enforcement.c
- gp_activetable.c
- gp_activetable.h
- quotamodel.c
- relation_cache.c
- relation_cache.h
- Use clang 13 to format the code
- Rename the job 'gate' to 'entrance', prepare adding 'exit' job
- Add clang-format as a entrance check into the PR pipeline
> Format the code and add clang-format to PR pipeline

- diskquota.c
- diskquota.h
- diskquota_utility.c
- gp_activetable.c
- quotamodel.c
and fix memory leak maybe
and improve performance
> clean up alloc and version check

- diskquota_utility.c
fix context corrupted when dirty data exist in pg_extension
> fix context corrupted when dirty data exist in pg_extension

- tests/CMakeLists.txt
Some tests were accidentally excluded in Debug build.
> Bring tests back on CI

- .clang-format
- diskquota.c
- diskquota_utility.c
- gp_activetable.c
- quotamodel.c
- relation_cache.c
Insert newline before `else` to keep align with gpdb repository.
> Insert newline before `else`

- diskquota.c
- tests/regress/expected/test_show_status.out
PostgreSQL use on/off for all bool variable.
soft limits: on (soft will works) / paused (soft limit not works)
hard limits: on (hard will works) / off (hard limit not works) / paused (hard limit not works)
> Use on/off in diskquota.status()

- tests/regress/expected/test_ctas_pause.out
- tests/regress/sql/test_ctas_pause.sql
Caused by the longger naptime for release build.
> Fix flaky ctas_pause on release build

- concourse/fly.sh
- concourse/pipeline/res_def.yml
This patch teaches concourse to fetch secrets from vault.
> [CI] Fetch secrets from vault.

- tests/regress/expected/test_ctas_role.out
- tests/regress/sql/test_ctas_role.sql
creating table runs too fast to trigger the hard quota limit.
> Fix flaky test test_ctas_role

- concourse/pipeline/res_def.yml
> Remove PR pipeline base branch

- quotamodel.c
There is a bug: removing TableSizeEntry from table_size_map by oid.
Actually the hash map key is TableKeyEntry. Fix it.
> Fix table entry key

- quotamodel.c
The #264 caused some segment ratio tests fail. The entry's relevant
fields need to be set at the end of the iteration. Otherwise, only the
first seg will pass the condition check.
> Fix regression caused by #264

- tests/regress/diskquota_schedule
> Enable tests

- quotamodel.c
Avoid dispaching reject map to segments when it is not changed
> Optimize dispatching reject map to segments

- gp_activetable.c
- tests/regress/expected/test_rejectmap_mul_db.out
- tests/regress/expected7/test_rejectmap_mul_db.out
- tests/regress/sql/test_rejectmap_mul_db.sql
When creating a new table, pg_type will be in active tables. Filter the system catalog table.
> Fix flaky test test_rejectmap_mul_db

- CMakeLists.txt
> Bump cmake min version to 3.20

- src/gp_activetable.c
Issue: #318 
The result buffer of SPI_execute is limited to 1GB. If the number of rows in `diskquota.table_size` exceeds 3 * 10^7 (500 segments with 60000 tables for example), `SPI_execute("select tableid, size, segid from diskquota.table_size")` will raise an error for `invalid memory alloc request size 1073741824 (context 'SPI TupTable')`.
We should fetch table-size entries by portions. Replace SPI_execute() with SPI_cursor_fetch() in load_table_size().
> Replace SPI_execute with SPI_cursor_fetch

- README.md
Hi
According to [CMakeLists.txt#L1](https://github.com/greenplum-db/diskquota/blob/gpdb/CMakeLists.txt#L1) the minimum version cmake version is 3.20.
> Update cmake version in README.

- concourse/scripts/test_diskquota.sh
So the script can be tested as well.
> Use install_gpdb_component in CI test

- src/diskquota.c
Note: `TextDatumGetCString()` returns a null-terminated CString.
```
[ 12%] Building C object CMakeFiles/diskquota.dir/src/diskquota.c.o
In file included from /home/v/workspace/diskquota/src/diskquota.h:16,
from /home/v/workspace/diskquota/src/diskquota.c:18:
/home/v/workspace/diskquota/src/diskquota.c: In function ‘diskquota_status_schema_version’:
/home/v/.local/gpdb7/include/postgresql/server/c.h:957:25: warning: ‘strncpy’ specified bound 64 equals destinatio
n size [-Wstringop-truncation]
957 |                         strncpy(_dst, (src), _len); \
|                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/v/workspace/diskquota/src/diskquota.c:1548:9: note: in expansion of macro ‘StrNCpy’
1548 |         StrNCpy(version, vv, sizeof(version));
|         ^~~~~~~
```
> Fix compiler warnings.

- src/diskquota.c
Fix bug produced by #339 
Co-authored-by: Xing Guo <admin@higuoxing.com>
> Fix bug: diskquota.status()

- concourse/pipeline/res_def.yml
> fix pipeline

- concourse/pipeline/res_def.yml
Get the latest package version for release resource.
> Fix pipeline.

- upgrade_test/alter_test.sh
Co-authored-by: Chen Mulong <chenmulong@gmail.com>
> Add a sleep in alter_test.sh

- src/diskquota.c
> Reduce the remain logs in bgworker.

- concourse/scripts/test_diskquota.sh
> Enable gpactivatestandby test

- tests/isolation2/expected7/test_relation_size.out
- tests/isolation2/sql/test_relation_size.sql
Co-authored-by: Chen Mulong <chenmulong@gmail.com>
Co-authored-by: Xing Guo <admin@higuoxing.com>
> Fix flaky test test_relation_size.

- src/diskquota.c
- src/diskquota.h
- src/quotamodel.c
Merge all types of quota info maps into one in each bgworker.
> Refactor quota info map

- src/diskquota.c
- src/diskquota.h
- src/diskquota_guc.c
- src/quota.c
- src/quota.h
- src/quota_config.h
- src/quotamodel.c
- remove diskquota_quota_info_entry_num
- move quota_info_map to quota.c
> Move quota

- src/quota.c
- src/rejectmap.c
- src/table_size.c
StringInfoData should be free in init/vacuum hashtable function.
> Fix memory leak

- CMakeLists.txt
- src/diskquota_bgworker.c
- src/diskquota_center_worker.c
- src/msg_looper.c
- src/msg_looper.h
- src/test_msg_loop.c
- add functions to copy the value from the message content.
- keep the name format of the macro definition the same.
> Add more function in message looper.

- src/msg_looper.h
While a message is created in client, the address is stored as the virtual memory address in client process. But server cannot access the address. So we need to store the address offset of the message content.
> Fix bug: the address of message cannot be access in another endpoint.

- .github/workflows/check.yml
> fix: update acions
