Makefile
README.md
diskquota--1.0.sql
diskquota.c
diskquota.h
diskquota_schedule
expected/test_extension.out
expected/test_fast_disk_check.out
gp_activetable.c
init_file
quotamodel.c
sql/prepare.sql
sql/test_extension.sql
sql/test_fast_disk_check.sql

table_size info are stored in the local memory of diskquota worker.
It cannot be accessed from other backend directly. This patch
stores the table_size info into user table diskquota.table_size for
fast table size check.
Diskquota worker initialization logic also changed to read table table_size
instead of calculate all the table's size by UDF pg_total_relation_size.
Detail design please refer to the Quota Status Checker part of wiki:
https://github.com/greenplum-db/gpdb/wiki/Greenplum-Diskquota-Design#design-of-diskquota

Add fast table size check feature.

---

enforcement.c
gp_activetable.c

GPDB hook for diskquota is merged. Some interface changed:
1 use unified name file_xxx_hook for both AO and heap tables.
2 parameter of hook function changed to RelFileNodeBackend.
3 remove hook in dispatcher.

Update hook interface and remove hook in dispatcher.

---

diskquota.c

1. Use %u to format Oid instead of %d
2. Use >=FirstNormalObjectId instead of >FirstNormalObjectId, as this issue disscussed in mail list

Fix format qualifier for Oid & use >=FirstNormalObjectId instead of >

---

gp_activetable.c

active_tables_map's key should be DiskQuotaActiveTableFileEntry instead of DiskQuotaActiveTableEntry.

Fix active_tables_map search key.

---

diskquota.c

BackgroundWorker need to do memset in PG_init after declare. Otherwise,
it may raise segment fault in RegisterBackgroundWorker()

initialize BackgroundWorker in PG_init function

---

concourse/scripts/test_diskquota.sh

When master failed, use gpactivatestandby to promote standby.
diskquota should also work on standby

Add diskquota standby test

---

diskquota.c
diskquota.h
enforcement.c
gp_activetable.c
quotamodel.c

diskquota workers may encounter error when sending SPI
queries to DB, these errors should be catched and workers
process could refetch database in the next loop instead of
exiting the worker processes directly.
Co-authored-by: Haozhou Wang <hawang@pivotal.io>

Add try catch for diskquota workers accessing DB.

---

diskquota.c
diskquota_schedule
expected/test_insert_after_drop.out
expected/test_primary_failure.out
sql/test_insert_after_drop.sql
sql/test_primary_failure.sql

1. Add a new test suit to make sure diskqouta is still working
when primary segment is failed, and mirror segment is swtich to
primary

Add test when primary segment is failed

---

diskquota--1.0.sql
diskquota_utility.c
expected/test_extension.out

Warning user to run select diskquota.init_table_size_table()
to build the table size information.

Add message when create extension and db is not empty

---

diskquota.c

As normal db connection, QD terminate QE processes if the connection is
idle for while. Import this mechanism in diskquota_launcher_process

Import idle worker terminate mechanism

---

diskquota.c
diskquota.h
gp_activetable.c

remove unused function get_all_tables_size.
we now get table size info from table_size table when
rebooting.
add new function pull_active_table_size_from_seg to make
gp_fetch_active_tables interface clear.
add some comments

Refactor gp_activetable

---

diskquota_schedule
diskquota_utility.c
expected/test_table_size.out
quotamodel.c
sql/test_table_size.sql

For toast table, QD side also has some table file. pretend diskquota
process as entrydb and grab these small file size.

calculate table size including QD side file size

---

diskquota.c

To give `bgworker` an `application_name` to indicate gpstop ignore when do sanity checking

Set BG worker application name

---

diskquota.c

The issue has been fixed in PR#6469 [https://github.com/greenplum-db/gpdb/pull/6469/]
So remove debug_query_string to avoid misuse the debug parameter

Remove debug_query_string when start diskquota

---

diskquota.c

1. Allowed GPDB crash when debug_query_string is null
before SPI_exectue

Set debug_query_string before SPI_exectue

---

expected/test_table_size.out
sql/test_table_size.sql

https://github.com/greenplum-db/gpdb/pull/11178 https://github.com/greenplum-db/gpdb/pull/11240 https://github.com/greenplum-db/gpdb/pull/11239 prevents some size-related function from running on master.
fix this by changing the test SQL.
```
gpdb@127:postgres> explain analyze verbose insert into buffer select oid, relname, pg_total_relation_size(oid) from pg_class, diskquota.table_size as dt where dt.tableid = oid and relname = 'a';
+---------------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                            |
|------------------------------------------------------------------------------------- …
```

avoid run pg_relation_size() on master, fix the table_size test case

---

diskquota.c
diskquota.h
diskquota_schedule
diskquota_schedule_int
expected/test_manytable.out
gp_activetable.c
gp_activetable.h
quotamodel.c
sql/test_manytable.sql

The issue described in #51 
in fact, there are 3 problems with this issue.
1. `diskquota.max_active_tables` GUC never take effect (fixed by leskin-in).
1. the `active_tables_map` actually store all table in prostgresql, not the table in `diskquota_namespace.database_list`.
1. `diskquota.monitor_databases` GUC never used, different from the document.
The third problem I think it is a feature now, fix it will break current usage.
This PR focus on fixing the second problem. 
In this PR I add shared memory hashtable `monitoring_dbid_cache`, which keeps track of `diskquota_namespace.database_list`.
When file_smgr* hook invoked, check the hash table first and filter out the dbid which should not be monitored.

Fix #51 when there ary many table in gpdb

---

diskquota--1.0.sql
diskquota.c
diskquota_utility.c
gp_activetable.c
quotamodel.c

A new shared memory is used in the segments to identify which table should be collected.
Also related to https://github.com/greenplum-db/diskquota/pull/54

Only collect active table info on diskquota enabled database

---

concourse/pipeline/pipeline.yml
concourse/scripts/test_diskquota.sh

* Fix the docker image
* Fix test_diskquota.sh
The current diskquota pipeline which using the pipeline.yml is: 
https://extensions.ci.gpdb.pivotal.io/teams/main/pipelines/diskquota-gpdb-6X-stable
This pipeline is failed now.
The testing diskquota pipeline for this pr is: https://extensions.ci.gpdb.pivotal.io/teams/main/pipelines/diskquota-gpdb-6x-stable-xiwang

Fix pipeline

---

README.md
concourse/scripts/test_diskquota.sh
concourse/scripts/upgrade_extension.sh
diskquota.h
diskquota_schedule
diskquota_utility.c
enforcement.c
expected/test_index.out
expected/test_table_size.out
gp_activetable.c
quotamodel.c
sql/test_index.sql
sql/test_table_size.sql

Support index in a different tablespace with the original table
* Use pg_table_size instead of pg_total_realtion_size to get the disk usage.
pg_table_size includes all forks, toast, and toast index, except the index.
* Add a function to get the list oids of the tables which the diskquota needs to care about in the database
firstly , get the tables which rekind is “r” or “m” and not system tables
```
"select oid from pg_class"
" where oid >= %u and (relkind='r' or relkind='m')",
FirstNormalObjectId);
```
then fetch the indexes of those tables and add them to the list.
Use the list of oids in init_table_size_table and calculate_table_disk_usage functions

Fix index tbl

---

diskquota--1.0--2.0.sql
diskquota--2.0--1.0.sql
diskquota--2.0.sql
diskquota.c
diskquota.h
diskquota_schedule
diskquota_utility.c
expected/test_pause_and_resume.out
quotamodel.c
sql/test_pause_and_resume.sql

This change adds two additional functions for user calling:
1. diskquota.pause_extension()
After this function being called, diskquota keeps counting
the disk usage but doesn't emit an error when the disk usage
limit is exceeded.
2. diskquota.resume_extension()
After this function being called, diskquota resumes to emit
an error when the disk usage limit is exceeded.

Add support for pausing and resuming the extension.

---

diskquota.h

Currently, we use DiskQuotaLocksItemNumber to count the number of
locks in diskquota. In de8418b, we forget to update it and it's causing
memory issues. To avoid such issues in future, we use
sizeof(DiskQuotaLocks) / sizeof(void*) to calculate the correct number
of locks.
Co-authored-by: Hao Zhang <hzhang2@vmware.com>

Fix incorrect number of locks in diskquota.

---

sql/init.sql

We have to create database 'diskquota' manually before running
regression tests. This change helps resolve it by creating the
database in the init stage.

Create database 'diskquota' before running regression tests.

---

Makefile
diskquota_schedule
expected/test_fetch_table_stat.out
gp_activetable.c
init_file
sql/test_fetch_table_stat.sql

Historically, diskquota fetches tables' size by applying pg_table_size()
on a given oid list. It may invoke pg_table_size() several times in one
transaction. In order to tolerate exceptions, we wrap it with PG_TRY()
and consume any errors throwed by pg_table_size() using FlushErrorState().
It has the following 2 potential risks.
1. Deadlock: Considering we have a table 't1' (reloid=oid1) and it has a
partition 't1_1_prt_11' (reloid=oid2).
When diskquota_fetch_table_stat(1, '{oid2, oid1}'::oid[]) is called
in session 'A', this UDF will invoke pg_table_size() on 't1_1_prt_11'
and 't1' respectively. When pg_table_size('t1_1_prt_11') throws an
exception, the AccessShareLock acquired from session 'A' will be held
until the whole transaction ends. At the same time, when another
session 'B' is …

Improve error handling in diskquota_fetch_table_stat().

---

diskquota.h
diskquota_utility.c
relation_cache.c

We should acquire relation_cache_lock when traversing relation_cache in remove_committed_relation_from_cache()

fix bug: acquire lock when traversing relation_cache

---

tests/regress/expected/test_relation_size.out
tests/regress/sql/test_relation_size.sql

Drop test table after testing diskquota.relation_size(), because the relation_entry the table in this test case will affect the next test case.

Fix test case bug

---

tests/regress/expected/test_blackmap.out
tests/regress/sql/test_blackmap.sql

This PR fixes incorrect JOIN condition in test_blackmap.sql. The
relfilenodes are not always different across segments. Hence, we should
add an additional JOIN condition to the test case or it will produce
unstable results.

Fix incorrect JOIN condition in test_blackmap.sql

---

diskquota.h
diskquota_utility.c
enforcement.c
gp_activetable.c
quotamodel.c
relation_cache.c
relation_cache.h
tests/regress/diskquota_schedule
tests/regress/expected/test_uncommitted_table_size.out
tests/regress/sql/test_uncommitted_table_size.sql

1. Add calculate_table_size() to calculate any table's size, including uncommitted table. In this procedure, no lock will be acquired, and the deadlock will be avoided.
2. Use SearchSysCache(), instead of relation_open(), to fetch table's pg_class.
3. Use diskquota_get_index_list(Oid) to fetch index list, instead of RelationGetIndexList(Relation), to avoid using relation_open(), which may cause deadlock.

calculate table size for hard limit

---

quotamodel.c
tests/isolation2/expected/test_blackmap.out
tests/isolation2/sql/test_blackmap.sql

This patch adds support for adding uncommitted relations to blackmap on
segment servers. Most of the codes share similar logic with adding
committed relations to blackmap. Test will be added in the next
following commits.

Add support for adding uncommitted relations to blackmap.

---

tests/init_file
tests/regress/expected/test_fetch_table_stat.out

This PR is trying to fix CI building failure by ignoring distribution
notice in CTAS statements.
Co-Authored-by: Hao Zhang <hzhang2@vmware.com>

Ignore distribution notice in regression tests.

---

relation_cache.c
tests/regress/expected/test_vacuum.out
tests/regress/sql/test_vacuum.sql

The modified table's relation_cache_entry is not be removed after vacuum full.
Use RelidByRelfilenode() to check whether the table is committed, and remove its relation_cache_entry.

Fix bug: table's relation_cache_entry is not be removed after vacuum full

---

tests/regress/sql/test_vacuum.sql

The SQL statement is not equal to expected output in test_vacuum.sql.

Fix test_vacuum.sql

---

tests/regress/expected/test_partition.out
tests/regress/expected/test_vacuum.out
tests/regress/sql/test_partition.sql
tests/regress/sql/test_vacuum.sql

Consider a user session that does a DELETE followed by a VACUUM FULL to
reclaim the disk space. If, at the same time, the bgworker loads config
by doing a SELECT, and the SELECT begins before the DELETE ends, while ends
after the VACUUM FULL begins:
bgw: ---------[ SELECT ]----------->
usr: ---[ DELETE ]-[ VACUUM FULL ]-->
then the tuples deleted will be marked as RECENTLY_DEAD instead of DEAD.
As a result, the deleted tuples cannot be removed by VACUUM FULL.
The fix lets the user session wait for the bgworker to finish the current
SELECT before starting VACUUM FULL .

Wait until deleted tuples are dead before VACUUM

---

diskquota.c
diskquota.h
quotamodel.c
tests/regress/diskquota_schedule
tests/regress/expected/test_pause_and_resume.out
tests/regress/sql/test_pause_and_resume.sql

Currently, diskquota.pause() only takes effect on quota checking.
Bgworkers still go over the loop to refreshing quota even if diskquota
is paused. This wastes computation resources and can cause flaky issues.
This fix makes bgworkers skip refreshing quota when the user pauses
diskquota entirely to avoid those issues. Table sizes can be updated
correctly after resume.

Refactor pause() to skip refreshing quota

---

diskquota.h
diskquota_utility.c
quotamodel.c

find a possible long time wait:
1. launcher deaded or in dead lock
2. do `create extension`
3. the default timeout is 120s, which is very long.
this PR adds a warning message after 3.6s waiting.
also this PR remove a lock `diskquota_locks.hardlimit_lock` and clear up some `include`

send a prompt if launcher crashed

---

tests/isolation2/sql/cleanup.sql
tests/regress/expected/clean.out
tests/regress/expected/test_drop_after_pause.out
tests/regress/expected/test_extension.out
tests/regress/expected/test_pause_and_resume_multiple_db.out
tests/regress/expected/test_recreate.out
tests/regress/sql/clean.sql
tests/regress/sql/test_drop_after_pause.sql
tests/regress/sql/test_extension.sql
tests/regress/sql/test_pause_and_resume_multiple_db.sql
tests/regress/sql/test_recreate.sql

Currently, deadlock can occur when
- A user session is doing DROP EXTENSION, and
- A bgworker is loading quota configs using SPI.
This patch fixes the issue by pausing diskquota before DROP 
EXTENSION so that the bgworker will not load config anymore.
Note that this cannot be done using object_access_hook() because
the extension object is dropped AFTER dropping all tables that belong
to it.

Pause before DROP EXTENSION

---

tests/regress/expected/test_blackmap.out
tests/regress/expected/test_ctas_tablespace_role.out
tests/regress/expected/test_ctas_tablespace_schema.out
tests/regress/expected/test_index.out
tests/regress/expected/test_mistake.out
tests/regress/expected/test_relation_size.out
tests/regress/expected/test_tablespace_role.out
tests/regress/expected/test_tablespace_role_perseg.out
tests/regress/expected/test_tablespace_schema.out
tests/regress/expected/test_tablespace_schema_perseg.out
tests/regress/sql/test_blackmap.sql
tests/regress/sql/test_ctas_tablespace_role.sql
tests/regress/sql/test_ctas_tablespace_schema.sql
tests/regress/sql/test_index.sql
tests/regress/sql/test_mistake.sql
tests/regress/sql/test_relation_size.sql
tests/regress/sql/test_tablespace_role.sql
tests/regress/sql/test_tablespace_role_perseg.sql
tests/regress/sql/test_tablespace_schema.sql
tests/regress/sql/test_tablespace_schema_perseg.sql

Test case test_primary_failure will stop/start segment to produce a
mirror switch. But the segment start could fail while replaying xlog.
The failure was caused by the deleted tablespace directories in previous
test cases.
This commit removes the "rm" statement in those tablespace test cases and
add "-p" to the "mkdir" command line. The corresponding sub-directories
will be deleted by "DROP TABLESPACE" if the case passes.
Relevant logs:
```
2022-02-08 10:09:30.458183 CST,,,p1182584,th1235613568,,,,0,,,seg1,,,,,"LOG","00000","entering standby mode",,,,,,,0,,"xlog.c",6537,
2022-02-08 10:09:30.458670 CST,,,p1182584,th1235613568,,,,0,,,seg1,,,,,"LOG","00000","redo starts at E/24638A28",,,,,,,0,,"xlog.c",7153,
2022-02-08 10:09:30.468323 …
```

Attempt to fix flaky test_primary_failure

---

diskquota--1.0--2.0.sql
diskquota--2.0--1.0.sql
diskquota--2.0.sql
diskquota.c
diskquota.h
quotamodel.c
tests/regress/expected/config.out
tests/regress/expected/test_ctas_pause.out
tests/regress/expected/test_ctas_role.out
tests/regress/expected/test_ctas_schema.out
tests/regress/expected/test_ctas_tablespace_role.out
tests/regress/expected/test_ctas_tablespace_schema.out
tests/regress/expected/test_drop_after_pause.out
tests/regress/expected/test_show_status.out
tests/regress/sql/config.sql
tests/regress/sql/test_ctas_pause.sql
tests/regress/sql/test_ctas_role.sql
tests/regress/sql/test_ctas_schema.sql
tests/regress/sql/test_ctas_tablespace_role.sql
tests/regress/sql/test_ctas_tablespace_schema.sql
tests/regress/sql/test_drop_after_pause.sql
tests/regress/sql/test_show_status.sql

- Change to use GUC to set hardlimit instead of udf. Since the hardlimit
setting needs to be persistent after postmaster restarting.
- Fix relevant test cases.

Use guc for hardlimit

---

diskquota.c

before: 
after:
with diskauota paused:
this PR avoids a busy loop in diskquota launcher when naptime = 0. save 100% (1core) CPU resource.

be nice with scheduler when naptime = 0

---

diskquota.c
diskquota.h

Currently, the Diskquota launcher first starts a worker, then creates
the worker entry. However, after the worker starts, it cannot find the
entry when trying to check the is_paused status. Also, after a GPDB
restart, when the QD checks whether the worker is running by
checking the epoch, it might also fail to find the entry.
This patch fixes the issue by first creating the worker entry then
starting the bgworker process.

Create worker entry before starting worker

---

diskquota--1.0.sql
diskquota--2.0.sql
diskquota.c
diskquota.h
diskquota_utility.c
gp_activetable.c
gp_activetable.h
quotamodel.c
tests/regress/diskquota_schedule
tests/regress/expected/test_update_db_cache.out
tests/regress/sql/test_update_db_cache.sql

The db cache stores which databases enables diskquota. Active tables
will be recorded only if they are in those databases. Previously,
we created a new UDF update_diskquota_db_list() to add the current db
to the cache. However, the UDF is install in a wrong database. As a
result, after the user upgrade from a previous version to 1.0.3, the
bgworker does not find the UDF and can do nothing.
This patch fixes the issue by removing update_diskquota_db_list() and
using fetch_table_stat() to update db cache. fetch_table_stat() already
exists since version 1.0.0 so that no new UDF is needed.
This PR is to replace PR #99 , and depends on PR #130 to fix a race
condition that occurs after `CREATE EXTENSION`.

Extend fetch_table_stat() to update db cache

---

concourse/fly.sh
concourse/pipeline/README.md
concourse/pipeline/base.lib.yml
concourse/pipeline/commit.yml
concourse/pipeline/dev.yml
concourse/pipeline/job_def.lib.yml
concourse/pipeline/pr.yml
concourse/pipeline/res_def.yml
concourse/pipeline/trigger_def.lib.yml
concourse/scripts/build_diskquota.sh
concourse/scripts/test_diskquota.sh

- Rewrite the pipelines by using ytt for code reuse.
- Add `fly.sh` for easier manipulating with pipelines.
- Create configs for pr, commit and dev pipelines.
- Fix the test task for rhel8.
- Use build/test images pair for all distros. And modify the
`build_diskquota.sh` so it won't need `Python.h` during the configure
stage.
- Fix the pipiline bug which a `ubuntu` test may use a `rhel6` diskquota
binary to do the test. That is caused by the same name of the task
output.
To replace #115

    Use ytt to create pipelines

---

diskquota--1.0.sql
diskquota--2.0.sql
diskquota.c
diskquota.h
diskquota_utility.c
gp_activetable.c
gp_activetable.h
quotamodel.c
tests/regress/diskquota_schedule
tests/regress/expected/test_update_db_cache.out
tests/regress/sql/test_update_db_cache.sql

The db cache stores which databases enables diskquota. Active tables
will be recorded only if they are in those databases. Previously,
we created a new UDF update_diskquota_db_list() to add the current db
to the cache. However, the UDF is install in a wrong database. As a
result, after the user upgrade from a previous version to 1.0.3, the
bgworker does not find the UDF and can do nothing.
This patch fixes the issue by removing update_diskquota_db_list() and
using fetch_table_stat() to update db cache. fetch_table_stat() already
exists since version 1.0.0 so that no new UDF is needed.
This PR is a revision of PR #138  , and depends on #130 to fix a race
condition that occurs after CREATE EXTENSION.

Extend fetch_table_stat() to update db cache v2

---

tests/regress/expected/test_update_db_cache.out
tests/regress/sql/test_update_db_cache.sql

Each time after CREATE EXTENSION, we need to wait until the db cache
gets updated. Otherwise no active table will be recorded.

Wait after CREATE EXTENSION

---

tests/isolation2/expected/test_relation_size.out
tests/isolation2/sql/test_relation_size.sql

This PR is trying to fix a race condition in `isolation2/test_relation_size`. It's observed in our CI https://extensions.ci.gpdb.pivotal.io/teams/main/pipelines/diskquota-pr-gpdb-6x/jobs/test_diskquota_pr/builds/30
-- edited by beeender start--
The pipeline has been renamed:
https://extensions.ci.gpdb.pivotal.io/teams/main/pipelines/DEPRECATED:diskquota-pr-gpdb-6x/jobs/test_diskquota_pr/builds/30
-- edited by beeender end--

Fix flaky test case in isolation2/test_relation_size.sql

---

diskquota--1.0.sql
diskquota.c
diskquota.h
diskquota_schedule
diskquota_utility.c
expected/test_primary_failure.out
expected/test_update_db_cache.out
gp_activetable.c
gp_activetable.h
quotamodel.c
sql/test_primary_failure.sql
sql/test_update_db_cache.sql

The db cache stores which databases enables diskquota. Active tables
will be recorded only if they are in those databases. Previously,
we created a new UDF update_diskquota_db_list() to add the current db
to the cache. However, the UDF is install in a wrong database. As a
result, after the user upgrade from a previous version to 1.0.3, the
bgworker does not find the UDF and can do nothing.
This patch fixes the issue by removing update_diskquota_db_list() and
using fetch_table_stat() to update db cache. fetch_table_stat() already
exists since version 1.0.0 so that no new UDF is needed.
This PR is a revision of PR #138 , and depends on #130 to fix a race
condition that occurs after CREATE EXTENSION.
Compared to 9684b635, the test has been modified to use pg_sleep()
instead of …

[Backport] Extend fetch_table_stat() to update db cache v2 (#151)

---

diskquota--1.0.sql

The added 'DISTRIBUTED BY' clause should have no impact on 1.x.

Keep the 1.0 sql the same with 1.x branch

---

tests/regress/diskquota_schedule
tests/regress/expected/test_ctas_before_set_quota.out
tests/regress/expected/test_ctas_no_preload_lib.out
tests/regress/expected/test_index.out
tests/regress/expected/test_role.out
tests/regress/sql/test_ctas_before_set_quota.sql
tests/regress/sql/test_ctas_no_preload_lib.sql
tests/regress/sql/test_index.sql
tests/regress/sql/test_role.sql

This patch adds test cases to ensure that diskquota works when table
is created before quota is set. Specifically,
- When diskquota is preloaded, quota usage is updated automatically
for each active table. Therefore, quotas work once they are set and no
more action is required from the user.
- When diskquota is NOT preloaded, no active tables will be recorded.
As a result, when diskquota is preloaded again, the user need to
SELECT diskquota.init_table_size_table(); and restarts GPDB manually
in order to update the quota usage.
This patch also fixes some minor issues in the existing cases.
This is to replace PR #125 .

Test when table is created before quota is set

---

concourse/pipeline/job_def.lib.yml
concourse/pipeline/res_def.yml
concourse/scripts/build_diskquota.sh
concourse/scripts/install_dep.sh
concourse/scripts/test_diskquota.sh
concourse/tasks/build_diskquota.yml
concourse/tasks/test_diskquota.yml

We need the archive extrace feature from cmake 3.18.
Before the new version landing to the test/build images, install them in
our ci scripts.
A cmake binary has been uploaded to the concourse gcs for faster
downloading.

Install the latest cmake on CI

---

CMakeLists.txt

CMAKE_INSTALL_PREFIX needs to be set as CACHE FORCE. Otherwise, next
time call 'make install' without source greenplum_path.sh, it will be
reset to '/usr/local'
See the example of CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT
https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT.html

Cache CMAKE_INSTALL_PREFIX

---

.gitignore
diskquota--2.0.sql
diskquota_utility.c
tests/regress/diskquota_schedule
tests/regress/expected/test_init_table_size_table.out
tests/regress/sql/test_init_table_size_table.sql

Add UDF `pull_all_table_size()` to accelerate `init_table_size_table()`. In this UDF:
1. we traverse pg_class to calculate the relation size of each relation;
2. parse the auxiliary table's name to get the relevant primary table's oid;
3. add the size of the auxiliary table to the primary table's size.
It can avoid multiple `relation_open()` and dispatching `pg_table_size()` to all segments.

Dispatch only once for all tables when init()

---

CMakeLists.txt
concourse/fly.sh
concourse/pipeline/commit.yml
concourse/pipeline/dev.yml
concourse/pipeline/job_def.lib.yml
concourse/pipeline/pr.yml
concourse/pipeline/res_def.yml
concourse/pipeline/trigger_def.lib.yml
concourse/scripts/build_diskquota.sh
concourse/tasks/build_diskquota.yml

Due to our upgrade design, the newly released diskquota should contain
all the so file of every latest minor release. The packaging system has
been implemented by cmake DISKQUOTA_PREVIOUS_INSTALLER.
This commit get the latest release through gcs regexp and pass it to the
build script.
The pipeline has been split into different jobs based on the OS type
because of:
- Easier to use the common resource name for build_diskquota.yml
- job_def.lib.yml becomes shorter
- Can span jobs into different concourse workers, which may bring some
better performance.
- Running flaky test again is easier.
Also a gate job has been added which is the main entrance for all
pipelines. In the future, we may want to have different gate job for
different pipelines, like a clang-format checking gate for the PR …

Pack the last released so in the pipeline

---

quotamodel.c

Reported by gcc 11.2.0:
quotamodel.c:2115:25: warning: ‘strncpy’ output truncated before
terminating nul copying 10 bytes from a string of the same length
[-Wstringop-truncation]
2115 |                         strncpy(targettype_str, "ROLE_QUOTA", 10);
|                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix gcc warning

---

cmake/Regress.cmake
tests/CMakeLists.txt
upgrade_test/CMakeLists.txt

my workflow:
- write many new tests.
- find -name '*.sql' | sed 's/sql/out/g' | xargs touch
- run those tests.
- check the output, if satisfied
- cp from results to expected
if `expected` and `result` in the same folder will be better.

cmake: also link RESULTS_DIR to working dir

---

tests/isolation2/expected/config.out
tests/isolation2/sql/config.sql
tests/regress/sql/config.sql
upgrade_test/sql/downgrade_extension.sql
upgrade_test/sql/upgrade_extension.sql

the old:
- set `shared_preload_libraries`
- reboot, load library to load GUC name
- set other GUC for diskquota
- reboot to make GUC take effect
the new one:
- set `shared_preload_libraries`
- set other GUC with `--skipvalidation`
- reboot to load library
remove one reboot step.
there is one GUC (diskquota.max_active_tables) related to shared memory, gpstop -u not work.
(maybe work but the test did not use gpstop -u)

ci: speed up the test

---

quotamodel.c

The ever growing part of memory contains the following pattern:
refresh_blackmap.*<segment_name><ip_address>:<port> pid=< pid>
The pattern contains info of segemnts. This indicates that the results
of dispatching refresh_blackmap() might not be freed properly.

Fix memory leak when refresh_blackmap()

---

CMakeLists.txt
cmake/Gpdb.cmake
upgrade_test/CMakeLists.txt

read the last version from `-DDISKQUOTA_LAST_RELEASE_PATH`
```
🚫 1.a.a => 3.a.a
🚫 1.0.a => 1.2.b
🚫 1.0.a => 1.0.b
✅ 1.0.a => 1.1.a
✅ 1.0.a => 2.0.a
✅ 1.0.a => 2.1.a
```

ci: add upgrade version naming convention check

---

CMakeLists.txt
cmake/Regress.cmake
concourse/pipeline/dev.yml
concourse/pipeline/job_def.lib.yml
concourse/pipeline/res_def.yml
concourse/scripts/build_diskquota.sh
concourse/scripts/entry.sh
concourse/tasks/build_diskquota.yml
diskquota.c
tests/CMakeLists.txt
tests/isolation2/expected/config.out
tests/isolation2/expected/reset_config.out
tests/isolation2/expected/test_postmaster_restart.out
tests/isolation2/sql/config.sql
tests/isolation2/sql/reset_config.sql
tests/isolation2/sql/test_postmaster_restart.sql
tests/regress/expected/config.out
tests/regress/expected/reset_config.out
tests/regress/expected/test_ctas_pause.out
tests/regress/expected/test_default_tablespace.out
tests/regress/expected/test_drop_after_pause.out
tests/regress/expected/test_update_db_cache.out
tests/regress/sql/config.sql
tests/regress/sql/reset_config.sql
tests/regress/sql/test_ctas_pause.sql
tests/regress/sql/test_default_tablespace.sql
tests/regress/sql/test_drop_after_pause.sql
tests/regress/sql/test_update_db_cache.sql

- Introduce macro DISKQUOTA_DEBUG through CMAKE_BUILD_TYPE. For the
debug build, check the macro and allow naptime = 0. The min naptime
for release build is 1 to prevent high cpu usage in user's
environment.
- Add EXCLUDE arg to Regree.cmake to skip some tests for the release
build since the release GPDB build doesn't support fault injector.
- Use GPDB release candidate to compile diskquota release. The release
candidate has assertion disabled in the pg_config.h.
- Set naptime=0 in the config.sql won't take effect for diskquota
release since it is less than the min value. So the naptime stays the
same (normally the default value, 2). This fails some of the test,
especially the hardlimit related ones. If the insertion takes less
time than naptime (2 seconds, normally), it fails since the …

Support release build

---

concourse/pipeline/dev.yml
concourse/pipeline/job_def.lib.yml
concourse/pipeline/pr.yml
concourse/pipeline/res_def.yml
concourse/pipeline/trigger_def.lib.yml

- Add a slack alert when commit pipeline fails
- Add exit job to set successful state. That state cannot be set by
individual job since at that point, the whole pipeline is not finished
yet.

slack-alert and PR pipeline fix

---

diskquota.c
diskquota_utility.c

Actually, errno *isn't* strictly an integer. It depends on your
operating system. Instead of formatting it as an integer, we should
transform it to C style string and format it as '%s'.
e.g., on my laptop the definition of errno is:
```C
/* The error code set by various library functions.  */
extern int *__errno_location (void) __THROW __attribute_const__;
```

Don't format errno as '%d' in error messages.

---

CMakeLists.txt
tests/data/current_binary_name

- Mac needs extra linker options that the symbols in the postgres
executable can be found.
- Mac's grep doesn't have '-P' option.
- To make a extension so file, we use a 'module' target instead of
'shared' on purpose. Since "A SHARED library may be marked with
the FRAMEWORK target property to create an macOS Framework."
Thus, the global link flags should be set through
CMAKE_MODULE_LINKER_FLAGS than CMAK_SHARED_LINKER_FLAGS.

Fix cmake build on Mac

---

concourse/README.md
concourse/fly.sh
concourse/pipeline/res_def.yml
tests/CMakeLists.txt

By the gcs resource regex rule, 6.99.99 will be matched as the most
recent gpdb release candidate, which is not what we want. It is a
testing version from release team. And due to the go regex
implementation, (!?) is not supported to filter out an exact string.
So the release pipeline is changed to use the most recent RELEASED gpdb
binary instead.

Use released gpdb instead of release candidate

---

diskquota--1.0--2.0.sql
diskquota--2.0.sql
diskquota.h
diskquota_utility.c
quotamodel.c
tests/isolation2/expected/test_per_segment_config.out
tests/isolation2/isolation2_schedule
tests/isolation2/sql/test_per_segment_config.sql
tests/regress/expected/test_tablespace_schema_perseg.out
tests/regress/sql/test_tablespace_schema_perseg.sql

If one tablespace segratio is configured,
this commit will make sure that ethier
the alredy existed (schema/role)_tablespace_quota
or new configs after this, will have the
same segratio.
1) Add a new quota type: TABLESPACE_QUOTA
used to store the tablespace segratio value
in quota_config table.
When set_per_segment_quota("xx","1.0) is
called, a new config will be added like:
` 97103 |         4 |            0 |        1`
0 means invalid quota configed
4 means TABLE_SPACE_QUOTA
2) Modify set_quota_config_internal to
support insert/delete/update new type config
3) Add function get_per_segment_ratio
it is called when insert new
(schema/role)_tablespace_quota.
"for share" is used to query segratio,it only
can keep the segratio is consistent in
"read committed" level.

Fix tablespace per segment ratio

---

.gitignore
diskquota--1.0--2.0.sql
diskquota--2.0--1.0.sql
diskquota--2.0.sql
diskquota.h
diskquota_utility.c
quotamodel.c
tests/isolation2/expected/test_per_segment_config.out
tests/isolation2/sql/test_per_segment_config.sql
tests/regress/diskquota_schedule
tests/regress/expected/test_tablespace_diff_schema.out
tests/regress/expected/test_tablespace_schema_perseg.out
tests/regress/sql/test_relation_size.sql
tests/regress/sql/test_tablespace_diff_schema.sql
tests/regress/sql/test_tablespace_schema_perseg.sql
upgrade_test/expected/2.0_catalog.out

When there are two namespace_tablespace_quota configurations with the
same schema but different tablespaces, removing one quota will remove
another one automatically. The same bug happens for the
role_tabelspace_quota case. The root cause of this bug is that we
can't distinguish these two quotas using only quotaType and targetOid
of diskquota.quota_config.
This PR fixes this by changing the meaning of targetOid column of
diskquota.quota_config table. When quotaType is
role_quota/schema_quota, targetOid refers to role_oid/schema_oid. When
quotaType is role_tablespace_quota/namespace_tablespace_quota,
targetOid refers to the rowId column of diskquota.target. This will
make it possible to distinguish two namespace_tablespace_quota with
the same schema and different tablespace. Because their …

Fix un-expected remove when two tablespace-quota has a same role or schema

---

tests/regress/expected/test_tablespace_diff_schema.out
tests/regress/sql/test_tablespace_diff_schema.sql

`diskquota.naptime` is 2 by default in release version. So it's better to wait for the bgworker to fresh blackmap after INSERT.

Wait next loop for bgworker to refresh before INSERT in testcase

---

gp_activetable.c
tests/regress/diskquota_schedule
tests/regress/expected/test_clean_blackmap_after_drop.out
tests/regress/sql/test_clean_blackmap_after_drop.sql

Fix hardlimit exceed after drop diskquota.
fix this scenario:
- create hard limit
- blackmap on segment was updated
- drop diskquota
- the blackmap on segment is not cleanup
use ObjectAccess hook on segment. when drop diskquota. clean up the in
memory blackmap.

clean blackmap after drop diskquota

---

diskquota.c

Diskquota workers dispatch queries periodically. For each dispatch,
one or more memory accounts will be created to keep track of the
memory usage. These accounts should be reset after the query
finishes to avoid memory leak.
Part of the stack trace of account creation looks like this:
```
fun:CreateMemoryAccountImpl
fun:MemoryAccounting_CreateAccount
fun:serializeNode
fun:cdbdisp_buildPlanQueryParms
fun:cdbdisp_dispatchX
fun:CdbDispatchPlan
fun:standard_ExecutorStart
fun:_SPI_pquery.constprop.11
fun:_SPI_execute_plan
fun:SPI_execute
fun:do_load_quotas
fun:load_quotas
fun:refresh_disk_quota_model
fun:disk_quota_worker_main
fun:StartBackgroundWorker
fun:do_start_bgworker
fun:maybe_start_bgworker
```
This patch fixes the memory leak issue by calling the reset function 
at the end of the …

Reset memory account to fix memory leak

---

quotamodel.c
tests/regress/expected/test_activetable_limit.out
tests/regress/expected/test_clean_blackmap_after_drop.out
tests/regress/sql/test_activetable_limit.sql
tests/regress/sql/test_clean_blackmap_after_drop.sql

release CI use naptime = 2.
add some `diskquota.wait_for_worker_new_epoch()` to make CI happy.
`invalidate_database_blackmap` on segment does work as expected, the old test is ﬂaky.
fix by correcting the search key. the key is different on master and segment.

some fix for release CI

---

quotamodel.c

And add contraries that the refresh_black_map() should not be executed
on QD.

Fix mistaken log statement

---

tests/regress/expected/test_tablespace_role_perseg.out
tests/regress/sql/test_tablespace_role_perseg.sql

"ALTER TABLE xx SET TABLESPACE" will change the relfilenode of
a table, it will copy files from old relfilenode directory to
the new one and delete all files when commiting the transaction.
As diskquota doesn't acquire a lock on the relation when
fetching table size, so if diskquota is collecting active
tables' size and another session is deleting a active table's
files under a old relfilenode directory in a changing
tablespace transaction, the diskquota may can't get all segment's
table size as files on part of segments have been deleted.
To fix it, we try to make a table to be an active table by
inserting data into it and wait the diskquota to recalculate
the tablesize after changing tablespace.

Fix change tablespace test case

---

diskquota_utility.c
tests/regress/expected/test_role.out
tests/regress/expected/test_schema.out
tests/regress/expected/test_tablespace_role.out
tests/regress/expected/test_tablespace_role_perseg.out
tests/regress/expected/test_tablespace_schema.out
tests/regress/expected/test_tablespace_schema_perseg.out
tests/regress/sql/test_role.sql
tests/regress/sql/test_schema.sql
tests/regress/sql/test_tablespace_role.sql
tests/regress/sql/test_tablespace_role_perseg.sql
tests/regress/sql/test_tablespace_schema.sql
tests/regress/sql/test_tablespace_schema_perseg.sql

the code transform all object name to lower case on purpose.
create schema "S1";
select * from diskquota.set_schema_quota("S1", '1MB');
ERROR:  schema "s1" does not exist

Fix set quota with upper case object name

---

diskquota.c
gp_activetable.c
quotamodel.c
relation_cache.c

Since we do NOT take any lock when accessing info of a relation,
cache invalidation messages may not be delievered in time each time
we SeearchSysCache() for relfilenode. As a result, the relfilenode may
be stale and the table size may be incorrect.
This patch fixes this issue by
- Checking for invalidation messages each time before
SearchSysCache(RELOID).
- Not removing a relation from active table map if the relfilenode
is stale.
Besides, since we do not remove the relfilenode if it maps to no
valid relation oid, we need remove those dangling relfilenodes
when unlink() to avoid memory leak.

Minimize the risk of stale relfilenodes

---

concourse/pipeline/job_def.lib.yml
concourse/pipeline/res_def.yml

"get" without "passed" will retrieve the latest content from a resource
that is not expected. Especially the release and dev pipelines share
the intermediates bucket.
- Move release intermediates to its own bucket
- Add passed the "get" step in the "exit_release" job, to make sure the
resource version generated from previous job will be consumed in this
job.

Release pipeline is publishing wrong intermediates

---

upgrade_test/CMakeLists.txt

git 1.7.1 dose not support `git diff /absolute/path/to/current/project`
make our CI happy.

Compatible with ancient git

---

concourse/scripts/build_diskquota.sh

cmake will look up c compiler by checking /usr/bin/cc. On CentOS7, that
symbolic linked to the gcc in the same directory. Although a newer gcc
is installed, cmake will not use the newer one.
We always export the CC and CXX, then the gcc/g++ in the $PATH will be
used.

Fix compiler version on concourse

---

CMakeLists.txt

Since we didn't implement anything in C++, let's invoke C compiler to link the target.
See: https://cmake.org/cmake/help/latest/prop_tgt/LINKER_LANGUAGE.html#prop_tgt:LINKER_LANGUAGE

[cmake] Use C compiler to link the target.

---

concourse/README.md
concourse/fly.sh

Concourse is deprecating some special characters in the pipeline name.
See details at https://concourse-ci.org/config-basics.html#schema.identifier
The pipelines will be named as:
<rel|pr|merge|dev>[_test].<project_name>[branch_name][.user_defined_postfix]
- Pipeline type 'release' is renamed to 'rel'
- Pipeline type 'commit' is renamed to 'merge'
- '_test' suffix will be added to pipeline type for pipeline debugging
- Instead of setting the whole name of pipeline, user can only set the
postfix.
Patch from https://github.com/pivotal/ip4r/pull/2

Scripts for new pipeline naming rules

---

CMakeLists.txt

The artifact was tared without "c", which is a tar only but not gzipped.
untar it with "xzvf" will report error:
"
tar  xzvf diskquota_rhel7_gpdb6.tar.gz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
"

Fix creating artifact

---

diskquota.c
tests/init_file
tests/regress/expected/test_extension.out
tests/regress/sql/test_extension.sql

Fix test failure on release pipeline
Regress tests failed on the release
pipeline due to the diskquota.naptime
is not 0. As diskquota launcher
first sleeps, then starts diskquota
workers. When naptime is not 0, workers
are started very late, then some tests
which checking them failed.
In this pr, fix the test by starting
diskquota workers in the launcher before
it sleeps. This makes diskquota workers
will be started immediately when the launcher
starts.
Also, increased the sleep time in
the tests.
Using get_database_name instead
of get_db_name, as worker_get_epoch
is called in a transaction.

Fix the test failure on release pipeline

---

quotamodel.c

Currently, diskquota supports max to 8000 tables, including partition tables. It may cause unexpected results if there are too many tables in the customer cluster.
This PR change `init_size` of table_size_map to 20000, instead of MAX_TABLES, so that we can
economize the actual usage of SHM. To handle scenarios with a large number of tables,
we set `max_size` to MAX_TABLES (1000000).
To avoid memory waste, only the master should be allocated shared memory for diskquota_launcher and diskquota_worker.

Support at least 20000 tables for each database

---

quotamodel.c

The scale of 50 databases with 200K tables is large enough, so we reduce MAX_TABLES to 200K to avoid memory waste.

Reduce MAX_TABLES to 200K.

---

quotamodel.c
tests/isolation2/expected/test_rejectmap.out
tests/isolation2/sql/test_rejectmap.sql

As the table has been created, its relid is a valid oid, then `check_rejectmap_by_reloid(reloid)` in `quota_check_common` will be executed and quota exceeded error will be reported with schema name or role name or tablespace name.
Why the test case can run successfully before, but sometimes fails? Because it adds the reject entry after starting inserting data into the table. If the inserting has hang up on `check_rejectmap_by_relfilenode` and then adding the reject entry, hardlimit will be triggered. Otherwise, softlimit will be triggered.

Fix test_rejectmap flaky test

---

diskquota.c
diskquota.h
diskquota_utility.c
test_util.sql
tests/regress/sql/config.sql

Rewrite the diskquota worker scheduler. Each db entry manages the running time by itself to make the scheduler more simple.
I have tested the performance, nearly the same as before.
Add a  UDF db_status to help debug or monitor the diskquota, related SQL is in test_util.sql. I didn't put it into diskquota--2.1.sql, because I don't want to users to use it now. I didn't use any shared lock when getting those status info, so they may be not consistent .

Rewrite the diskquota worker scheduler

---

gp_activetable.c
quotamodel.c
relation_cache.c
tests/isolation2/expected/test_relation_cache.out
tests/isolation2/isolation2_schedule
tests/isolation2/sql/test_relation_cache.sql

Previously, users will see the information of tables in db2 when accessing db1 and executing `select diskquota.show_relation_cache()`.  Meanwhile, if db1's bgworker can see the table in db2, the performance will be influenced, because the table size in db2 will be calculated although it is not useful for db1 diskquota.
This PR has added a judgment to prevent this situation.

Fix bug: relation_cache cannot isolate table info for each database

---

diskquota_utility.c
gp_activetable.c
tests/regress/expected/test_init_table_size_table.out
tests/regress/expected/test_relkind.out
tests/regress/sql/test_init_table_size_table.sql
tests/regress/sql/test_relkind.sql

Previously, if we create a type/view before `create extension diskquota`, it is necessary to call `diskquota.init_table_size_table()`, but the size of the type/view does not count for diskquota. This PR modifies the condition for pg_class selection and relation_cache to filter the useless relation type.

Filter the useless relation type.

---

monitored_db.c
tests/init_file

Flaky has been seen like:
```
test test_extension           ... FAILED (176.97 sec)  (diff:0.15 sec)
...
SELECT diskquota.wait_for_worker_new_epoch();
+WARNING:  [diskquota] database "contrib_regression" not found (monitored_db.c:229)
...
wait_for_worker_new_epoch
---------------------------
t
```
Since there is a 'gpstop -ra' at the top of the test, there is a chance
that when the following 'wait_for_worker_new_epoch()' runs, the luancher
has not been fully initialized yet. In this case, 'wait_for_worker_new_epoch()'
prints timeout warnings and retry, until it succeeds. Warning here is
not an issue, just ignore it.

Fix flaky "database not found"

---

diskquota.c
tests/regress/expected/test_worker_schedule.out
tests/regress/sql/test_worker_schedule.sql

If we set the diskquota.max_workers max value to be max_worker_processes, when max_worker_processes is less than 10 and we set diskquota.max_workers value more than max_worker_processes, the cluster will crash.
Set the max value to 20, when the max_worker_processes is less than the diskquota.max_workers, diskquota can work, only some parts of the databases can not be monitored as diskquota can not start bgworkers for them.

Change the max value of diskquota.max_workers to 20

---

tests/isolation2/expected/test_relation_cache.out
tests/isolation2/sql/test_relation_cache.sql

'Pause' needs to be called before the 'DROP EXTENSION'

Missing pause causes deadlock flaky

---

diskquota.c
quotamodel.c

When database is not ready, diskquota loops to check it. So need to call MemoryAccounting_Reset.
Similar to the commit: 218ec93ee14db3e6e63491e7908631f236674d9e

Fix memory leak when database is not ready

---

diskquota.c
tests/isolation2/expected/config.out
tests/regress/expected/config.out

Change the default value of `diskquota.max_active_tables` from 1M to 300K, and the memory usage relevant is reduced from 300MB to 90MB.

Change `diskquota.max_active_tables` default value to reduce memory cost

---

gp_activetable.c
quotamodel.c

Refactor the structure of `TableSizeEntry` to reduce memory usage.
Previously, the size of each table in each segment should be maintained in `TableSizeEntry`, which wastes lots of memory. In this PR, we refactor the `TableSizeEntry` to:
```
struct TableSizeEntry
{
Oid    reloid;
int    segid;
Oid    tablespaceoid;
Oid    namespaceoid;
Oid    owneroid;
uint32 flag;
int64 totalsize[SEGMENT_SIZE_ARRAY_LENGTH];
};
```
In this way, we can maintain multiple sizes in one `TableSizeEntry` and efficiently save memory usage.
- For 50 segments: reduced by 65%.
- For 100 segments: reduced by 82.5%.
- For 101 segments: reduced by 65.3%.
- For 1000 segments: reduced by 82.5%.

Reduce memory usage.

---

diskquota.c
upgrade_test/CMakeLists.txt

By default DISKQUOTA_DDL_CHANGE_CHECK is ON which will check the DDL
change and report errors if the previous version of so files don't
exist.
For dev:
cmake .. \
-DPG_CONFIG=/path/to/pg_config \
-DDISKQUOTA_DDL_CHANGE_CHECK=OFF
to disable the check
And fixed a build warning.

Add cmake opt DISKQUOTA_DDL_CHANGE_CHECK

---

quotamodel.c
tests/regress/diskquota_schedule
tests/regress/expected/test_rejectmap_mul_db.out
tests/regress/sql/test_rejectmap_mul_db.sql

Previously, refresh_rejectmap() cleared all entries in rejectmap, including other databases' entries, which causes hardlimit can not to work correctly. This commit fixed the bug.
Meanwhile, this PR fixed a bug: soft-limit rejectmap entries should not be added into `disk_quota_reject_map` on segments.

Fix bug: rejectmap entries should not be removed by other databases.

---

tests/isolation2/expected/test_fast_quota_view.out
tests/isolation2/sql/test_fast_quota_view.sql

- Drop the table space before rm directory.
- '-f' to alway force rm.
- '-- start-ignore' doesn't seem to be working with retcode since retcode
will add '-- start/stop-ignore' pair automatically to ignore the
output, and the nested start/stop ignore doesn't seem to be handled
well by the ancient perl script. Refer to
'src/test/isolation2/sql_isolation_testcase.py'.
Seen flaky tests as below:
```diff
root@96831b9f-9150-4424-63a7-abe8f18c144e:/tmp# cat /home/gpadmin/diskquota_artifacts/tests/isolation2/regression.diffs
--- \/tmp\/build\/4eceba44\/bin_diskquota\/tests\/isolation2\/expected\/test_fast_quota_view\.out	2022-12-12 13:20:56.729354016 +0000
+++ \/tmp\/build\/4eceba44\/bin_diskquota\/tests\/isolation2\/results\/test_fast_quota_view\.out	2022-12-12 13:20:56.733354401 +0000
@@ -175,9 …
```

Fix flaky test_fast_quota_view

---

concourse/pipeline/job_def.lib.yml
concourse/pipeline/res_def.yml

- Switch GPDB binary to release-candidate for release build.
- Remove test_task from the release pipeline.

CI: Fix pipeline

---

cmake/Regress.cmake

Isolation2 compilation command is removed by #285 . We add it into Regress.cmake in this commit.
Co-authored-by: Xing Guo <higuoxing@gmail.com>

Add command to compile isolation2.

---

gp_activetable.c
tests/isolation2/expected/test_truncate.out
tests/isolation2/expected/test_vacuum.out
tests/isolation2/expected7/test_truncate.out
tests/isolation2/expected7/test_vacuum.out
tests/isolation2/sql/test_truncate.sql
tests/isolation2/sql/test_vacuum.sql

- Fix flaky test test_ctas_before_set_quota. pg_type will be an active table
after `CREATE TABLE`. It does not affect the function of diskquota but
makes the test results unstable. In fact, we do not care about the table
size of the system catalog table. So we simply skip the active table oid
of these tables.
- Fix test_vacuum/test_truncate. gp_wait_until_triggered_fault
should be called after gp_inject_fault_infinite with suspend flag.
Co-authored-by: Xing Guo <higuoxing@gmail.com>
Co-authored-by: Xiaoran Wang <wxiaoran@vmware.com>

Fix flaky test

---

CMakeLists.txt
concourse/pipeline/job_def.lib.yml
concourse/scripts/build_diskquota.sh
concourse/scripts/test_diskquota.sh
concourse/tasks/build_diskquota.yml
upgrade_test/CMakeLists.txt

Revert some modification from #285 .
- Add last_released_diskquota_bin back for CI.
- Enable upgradecheck.
- Add `-DDISKQUOTA_LAST_RELEASE_PATH` for cmake.

Enable upgrade test for CI

---

.editorconfig
cmake/Regress.cmake
concourse/pipeline/job_def.lib.yml
tests/CMakeLists.txt

Due to the release build change for GP7, the fault injector doesn't work
with release build. So, all the tests are temporally disabled for GP7
release.
- Add 'EXCLUDE_FAULT_INJECT_TEST' to Regress.cmake, so it will be smart
enough to check if there are any fault injector case in the give tests
set. Ignore them if so.
- Skip the fault injector tests for release build.
- Enable the CI test task for GP7.

Skip fault injector case for release build

---

diskquota.h
diskquota_utility.c
gp_activetable.c
relation_cache.c

This PR replaces relation_open()/relation_close() with RelationIdGetRelation()/RelationClose() to avoid deadlock. We can only call relation_open()  with AccessSharedLock in object_access_hook(OAT_POST_CREATE) in GPDB7, which may cause deadlock. While RelationIdGetRelation()/RelationClose() just locks pg_class instead of user-defined relation, so we use these functions to get the information of relations.

Replace relation_open/relation_close with RelationIdGetRelation/RelationClose.

---

tests/regress/expected/test_rejectmap_mul_db.out
tests/regress/sql/test_rejectmap_mul_db.sql

There are some bugs in active tables, but we are not intended to fix them now. So just bring back the pause in the sql to make the test can run success at most time.

Fix flaky test of test_rejectmap_mul_db

---

concourse/pipeline/res_def.yml

The release candidate contains the build number now. Change the regex to
match the latest release candidate for release pipeline.

Fix gpdb release binary regex

---

concourse/pipeline/job_def.lib.yml
concourse/pipeline/res_def.yml
tests/init_file
tests/regress/expected/test_clean_rejectmap_after_drop.out
tests/regress/expected/test_ctas_role.out
tests/regress/expected/test_ctas_tablespace_role.out
tests/regress/expected/test_mistake.out
tests/regress/expected/test_rename.out
tests/regress/expected/test_role.out
tests/regress/expected/test_schema.out
tests/regress/expected/test_tablespace_role.out
tests/regress/expected/test_tablespace_role_perseg.out
tests/regress/expected/test_temp_role.out
upgrade_test/expected/1.0_set_quota.out
upgrade_test/expected/2.0_set_quota.out
upgrade_test/expected/2.1_set_quota.out
upgrade_test/expected/2.2_set_quota.out
upgrade_test/init_file

```
NOTICE:  resource queue required -- using default resource queue "pg_default"
```
has been removed in gpdb7 82851a0b85 . Ignore it in the tests.

Resource change for gpdb7 binary

---

src/diskquota.c
src/gp_activetable.c
tests/isolation2/expected/test_ereport_from_seg.out
tests/isolation2/isolation2_schedule
tests/isolation2/sql/test_ereport_from_seg.sql
tests/regress/diskquota_schedule
tests/regress/expected/test_readiness_logged.out
tests/regress/sql/test_readiness_logged.sql

A dead loop in bgworker will happen following these steps:
- Bgworker executes a query by SPI_execute().
- Some QE's generate notices(for example, the crash of this server) and pass them to QD(bgworker).
- The bgworker wants to forward notices to the client in SPI_execute(). But there's no client for bgworker to establish the pq connection, which will cause a dead loop for bgworker.
The diskquota bgworker will always wait for internal_putbytes(), and can not update the table size.
The problem is caused by initializing MyProcPort in bgworker. In GPDB, if `MyProcPort == NULL`, the notice will never be forwarded to the client.
```
/*
* If MyProcPort is NULL, there is no client, so no need to generate notice.
* One example is that there is no client for a background worker.
*/
if (!res || …
```

Fix bug: bgworker enters infinite loop after receiving notices from QE.

---

tests/init_file

Some hint/notice causes the partition table test flaky. We just need to ignore them.

Ignore some hint/notice for GPDB7

---

src/quotamodel.c

If the number of entries needed to be updated in diskquota.table_size is too many, the size of StringBuffer will exceed 1GB and raise an error `Cannot enlarge string buffer containing 1073741807 bytes by 20 more bytes.`.
We should limit the number of entries in update statement to 1000000 every times to ensure the string buffer size does not exceed 1GB.

Split update SQL statement for diskquota.table_size

---

src/diskquota.c

When with often signals receiving diskquota may call refresh_disk_quota_model frequently than diskquota_naptime.
When receiving a signal, the time waiting for latch `sleep_time` will be smaller than `diskquota_naptime`. We should skip refresh_disk_quota_model() when `sleep_time < diskquota_naptime`.

Skip refresh_disk_quota_model() when receiving a signal

---

src/diskquota.c

To achieve upgrading directly from 2.0 to 2.2, we should do the following things:
- cherry-pick this PR in diskquota-2.0, diskquota-2.1 and diskquota-2.2.
- set the shared_preload_libraries as `diskquota-2.2`: `gpconfig -c shared_preload_libraries -v 'diskquota-2.2'`
- restart cluster: `gpstop -ar`
- execute the following SQLs:
```
ALTER extension diskquota update to '2.2';
```

Enable continuous upgrade.

---

upgrade_test/CMakeLists.txt

- Because of 97f1f9b46b, the sql file directory has been changed. The
sql version check wouldn't work since it cannot find the sql files
anymore. Change it to the correct ddl directory.
- 'exec_program' is deprecated, use 'execute_process' instead.
- 'git tag | sort' returns the latest version among all branches, but
not the closest tag to the current commit. Use 'git describe --tags'
instead. So the upgrade version check will work for the 2.1.x patch
release.

Fix upgrade version check

---

concourse/pipeline/commit.yml
concourse/pipeline/pr.yml
concourse/pipeline/release.yml

After creating extension, the `diskquota.state` is always `unready` due to the change https://github.com/greenplum-db/gpdb/pull/15239. It makes the test timeout. We disable the job of gp7 in release/pr/merge pipeline until the problem is fixed.

Remove gp7 from pipeline

---

concourse/scripts/test_diskquota.sh
upgrade_test/alter_test.sh

Change the CI pipeline to release diskquota for GP7.
TODO:
- enable regress test on CI.
- enable activatestandby test for GP7 on CI.
- fix regress test for GP7. The view in GP7 will be treated as a relation by diskquota. After `CREATE EXTENSION`, the test case should execute `SELECT diskquota.init_table_size_table()` to make the diskquota.state ready on GP7.

Release/gp7 2.2.2

---

control/ddl/diskquota--2.3.sql

All tables in diskquota use primary keys. Unique index tables are created for primary keys. Unique index tables can not be created for tables with the option appendonly=true. This issue only occurs in gp6 since `set gp_default_storage_options='appendonly=true';` is disabled in gp7.
1) build diskquota extension
2) append it to shared_preload_libraries
3) create diskquota database
4) restart cluster
5) execute in the postgres (on any other) database:
```
set gp_default_storage_options='appendonly=true';
create extension diskquota;
```
```
ERROR:  append-only tables do not support unique indexes
```
Add appendonly=false to each table with the primary key.
This PR is refactored from #341 
Co-authored-by: Evgeniy Ratkov <e.ratkov@arenadata.io>

fix creating extension with global option appendonly=true.

---

src/diskquota.c

Several commits (05da9d4 and 86ff586) in diskquota 2.2.2 eased restrictions for extension initialization checks to make it possible to update extension. But these changes make it possible to run diskquota queries against uninitialized extension too. That leads to segmentation fault on segments as far as shared structures isn't initialized properly.
issue: #360 
During the upgrade procedure, when diskquota.so is not in shared_preload_libraries, check whether the current version is the final version:
- If yes, throw an error to the user.
- Otherwise, return from _PG_init().

Fix continuous upgrade

---

CMakeLists.txt
concourse/pipeline/commit.yml
concourse/pipeline/pr.yml

- Fix the compilation issue caused by GP7. `libpq.so` needs to be linked. See https://github.com/greenplum-db/gpdb/pull/16234.
- Add GP7 jobs back to the pipeline.

Fix compilation issue caused by GP7

---

src/diskquota.c
src/quotamodel.c

`diskquota.max_quotas` shows the max number of quotas on the cluster.
In the current version of diskquota, quotas means:
- role
- schema
- role_tablespace
- schema_tablespace
The number of quota =
role + schema + (role * tablespace) + (schema * tablespace).
This PR is waiting for #369

Add GUC diskquota.max_quotas

---

src/diskquota.c
src/diskquota.h
src/quotamodel.c

GUC diskquota.max_quota_probes indicates the number of quota probes pre-allocated at the cluster level. Diskquota requires thousands of probes to collect different quota usage in the cluster, and each quota probe is only used to monitor a specific quota usage, such as how much disk space a role uses on a certain tablespace. Even if you do not define the corresponding disk quota rules, the corresponding probe will continue to run in the background.  
The max number of active probes equals `role_num + schema_num + role_num * tablespace_num + schema_num * tablespace_num`. role_num is the number of role in the cluster. tablespace_number is the number of tablespace in the cluster. schema_num is the total number of schema in all databases. database_number is the number of databases. For …

Rename diskquota.max_quotas to diskquota.max_quota_probe

---

src/quotamodel.c

- DDL message is only used on master, so it is unnecessary to allocate the memory on segments.
- The launcher shmem should not be initialized on segments.

Fix wrong shmem allocation.

---

control/ddl/diskquota--3.0.sql
src/diskquota_bgworker.c
src/diskquota_center_worker.c
src/message_def.h
src/quotamodel.c
src/relation_cache.c
src/relation_cache.h
src/table_size.c
src/table_size.h
src/toc_map.c

bgworker behavior:
- collect active table size from segments.
- get relation oid list in the current database.
- generate local_table_size_map.
- send database oid, relation oid list and local_table_size_map
to center worker.
center worker behavior:
- find table_size_map by database oid.
- traverse the relation oid list, and  set TABLE_EXIST flag
for each entry in table_size_map.
- update table_size_map by local_table_size_map.
- remove the entry without TABLE_EXIST flag.
TODO:
- update quota when the table size is changed.
- update rejectmap in center worker
- send rejectmap to bgworker
- send rejectmap to segments
- replace diskquota.table_size with view and UDF
- when drop extension, vacuum table size map
in center worker
- do not load table size from diskquota.table_size
when is_init …

Refresh table size map in center worker

---

src/quotamodel.c

refresh_rejectmap looks for a tuple using SearchSysCacheCopy1 which retrieves a copy of the tuple allocating memory for it. However, refresh_rejectmap didn't free these tuple copies after use. If lots of oids were passed, diskquota could work incorrectly because of huge memory leak. This patch frees these tuples and prevents memory leaks.

Free tuple after use in refresh_rejectmap

---

src/diskquota.h
src/diskquota_utility.c
src/quotamodel.c
tests/isolation2/expected/test_dropped_table.out
tests/isolation2/expected/test_temporary_table.out
tests/isolation2/expected7/test_dropped_table.out
tests/isolation2/expected7/test_temporary_table.out
tests/isolation2/isolation2_schedule
tests/isolation2/sql/test_dropped_table.sql
tests/isolation2/sql/test_temporary_table.sql

Invalidate diskquota.table_size entries during startup
Diskquota calculates sizes and stores information in the diskquota.table_size
table periodically with a pause in diskquota.naptime, 2 seconds by default.
If we restart the cluster during this pause, then diskquota will lose all
changes that have occurred since the last save to the diskquota.table_size
table. We could create temporary tables, wait when it will be flushed to
diskquota.table_size table, restart the cluster, and diskquota would remember
the information about the temporary tables. Or we could delete the tables,
restart the cluster, and again diskquota will remember information about the
deleted tables. This happens because at the start of the cluster, diskquota
remembers all the information written to the …

Invalidate diskquota.table_size entries during startup
